version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Nothing to do in the install java phase
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/st00-e2edemo.war
    - appspec.yml
    - scripts/before_install.sh
    - scripts/after_install.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh

